Added maintenance mode.
savoirfairelinux/ansible-django pull request #11
Opened 2017-02-14 21:05 UTC by desecho

2017-02-15 15:14 UTC, ellmetha requested changes
I think that you forgot to include the `maintenance.html` template into your branch! :smile_cat:

2017-02-15 15:14 UTC, ellmetha commented on defaults/main.yml
> +django_maintenance_path: "{{ django_project_path }}/maintenance"
Could you add a comment here in order to explicit the purpose of this directory ? :wink: eg. explaining that it is used to store maintenance pages, etc.

2017-02-15 15:47 UTC, desecho commented
J'ai fait des changements

2017-02-15 19:22 UTC, hsoft commented
I've tested it on our local dummy django projet, in vagrant mode, and this PR breaks the scenario where we have a `django_project_symlink_dest` because the maintenance folder was created and then the symlink can't happen.

This failure highlights that the `maintenance` folder should be in `{{ django_path }}/maintenance` instead of `{{ django_project_path }}/maintenance`.

2017-02-16 17:52 UTC, desecho commented
I changed the path to `{{ django_path }}/maintenance`.

2017-02-16 19:23 UTC, ellmetha approved these changes

2017-02-16 19:54 UTC, ghost approved these changes

2017-02-16 19:54 UTC, merged