nginx: add ability to restrict /media/ access to one or many IP/CIDR/domain
savoirfairelinux/ansible-django pull request #12
Opened 2017-11-10 20:47 UTC by bardessaoli

2017-11-10 21:12 UTC, peakwinter requested changes

2017-11-10 21:12 UTC, peakwinter commented on defaults/main.yml
> +nginx_restrict_media_access_to: {}
```yaml
nginx_restrict_media_access_to: []
```

2017-11-10 21:22 UTC, bardessaoli commented
Corrected!

2017-11-11 03:22 UTC, peakwinter approved these changes

2017-11-11 03:22 UTC, merged